### ISSUE TITLE
How can I create a container with "stamps", the ability to prevent dragging into an area within a container

### ISSUE THREAD

**Issue by LordZardeck** [desandro/draggabilly#100]
I am making an app where I have "windows" floating on the screen. Then i have "cards" that are dragged around the entire screen. I don't want the "cards" able to be dragged "behind" the "windows". In other MetaFizzy project such as Masonry, you can "stamp" out an area that is ignored for layouts. Is this possible with this library? If not, is there a way to "hook" into this library to add that functionality myself? If so, where would I begin?

**Comment by desandro** [comment]
You might want to look into how [Packery handles dragging](https://github.com/metafizzy/packery/blob/v1.4.2/js/packery.js#L382). Setting no-drag areas can be complicated. It's actually an unresolved issue with Packery metafizzy/packery#203

**Comment by LordZardeck** [comment]
@desandro Would I have to fork [draggabilly](https://github.com/desandro/draggabilly) in order to make this work? Or is there some events/plugin system that I can use in order to not modify core code

**Comment by desandro** [comment]
You can use Draggabilly's events API. You don't need to fork it and modify its source. Packery uses standard Draggabilly events.

**Comment by LordZardeck** [comment]
@desandro Looking at the source of [draggabilly](https://github.com/desandro/draggabilly/blob/master/draggabilly.js#L374) I see that an event is dispatched, but I don't see a way to override/prevent a drag from the event.
