### ISSUE TITLE
Disabling this.setLeftTop(); on DragEnd

### ISSUE THREAD

**Issue by jamielob** [desandro/draggabilly#103]
Hi!

I need to disable this.setLeftTop(); on DragEnd for a couple of use cases so that I can do my own animations using just Transform.  I can overwrite the DragEnd prototype, but then I don't get to use it in the other places I need it to do it's magic as normal.

Any suggestions?

Thanks,

Jamie

**Comment by desandro** [comment]
Duck punch it!

```js
var _dragEnd = Draggabilly.prototype.dragEnd;
Draggabilly.prototype.dragEnd = function( event, pointer ) {
  if ( this.isSpecial ) {
    // do special stuff
  } else {
    // not special, do regular stuff
    _dragEnd.apply( this, arguments );
  }
};
```

**Comment by jamielob** [comment]
Beautiful! I'll get the monkey out.
