### ISSUE TITLE
Relative units and snap to grid

### ISSUE THREAD

**Issue by lmartins** [desandro/draggabilly#104]
Is it possibile to have a flexible grid, where the grid units all have relative sizes (%, ems or view port units) and have them still snap to grid?

I've looked into https://github.com/desandro/draggabilly/issues/65 but that seems still to work only with absolute values.

Thanks.

**Comment by desandro** [comment]
Thanks for this feature request. **+1 this issue** if you would like to see this feature added.

Currently, no. `grid` option values are explicit pixel values. You can change them, but it requires adding your own JS.

**Comment by desandro** [comment]
Looks like no one else +1'd this feature request, so I'm going to close it. Thanks again for reporting this issue! 🍓
