### ISSUE TITLE
IE10+ - drag an scrollable element keeps moving after drag end

### ISSUE THREAD

**Issue by cxq** [desandro/draggabilly#106]
Hi,

I've encountered an issue while scrolling the element using the mouse, 

1) click on the scrollbar to move the scroll position
2) when you mouse up, the element still follow your mouse.

http://jsfiddle.net/v9b8m4fL/3/

Regards,
Xiu qiang

**Comment by desandro** [comment]
Thanks for reporting this bug. I'm not sure if there's a good solution here. I don't believe there's any API for detecting when a scrollbar has been clicked.
