### ISSUE TITLE
How can i drag elements from sidebar (overflow-y: auto) to container ?

### ISSUE THREAD

**Issue by ZsharE** [desandro/draggabilly#107]
Demo: http://codepen.io/desandro/pen/cbhDG

I want to be able to drag a slide from sidebar to container and drop there. Is this possible ?
For example with jQuery UI Draggable you can achieve this result by using an option called { "helper": "clone" }. I didn't find something like that in documentation.

Waiting for an answer,
Thanks !

**Comment by desandro** [comment]
You can do this with Draggabilly, but only by adding your own remove+drop+clone behavior code, making use of Draggabilly's API. Sorry, but there's no easy way to this now.
