### ISSUE TITLE
Keeping existing transforms

### ISSUE THREAD

**Issue by peterbe** [desandro/draggabilly#110]
When you start dragging an element you can see that it gets its `transform: translate3d(Xpx, Ypx, 0)` set. And then, when you stop dragging it changes that to `top: Xpx; left: Ypx` and the `transform` property is removed. 

This makes it impossible to set a `transform: rotate(90deg)` on the element additionally.

**Comment by desandro** [comment]
Thanks for this feedback. We already have an issue opened for this request. **Add your +1** to #92
