### ISSUE TITLE
Webpack problem of include draggabilly npm package

### ISSUE THREAD

**Issue by geohuz** [desandro/draggabilly#111]
npm install draggabilly, and import Draggabilly from 'draggabilly', got the following error message:

ERROR in ./~/draggabilly/draggabilly.js
Module not found: Error: Cannot resolve module 'classie/classie' in /node_modules/draggabilly
 @ ./~/draggabilly/draggabilly.js 13:4-21:8

ERROR in ./~/draggabilly/draggabilly.js
Module not found: Error: Cannot resolve module 'get-style-property/get-style-property' in /node_modules/draggabilly
 @ ./~/draggabilly/draggabilly.js 13:4-21:8

ERROR in ./~/draggabilly/~/get-size/get-size.js
Module not found: Error: Cannot resolve module 'get-style-property/get-style-property' in /node_modules/draggabilly/node_modules/get-size
 @ ./~/draggabilly/~/get-size/get-size.js 241:2-70

ERROR in ./~/draggabilly/~/unidragger/~/unipointer/unipointer.js
Module not found: Error: Cannot resolve module 'eventEmitter/EventEmitter' in /node_modules/draggabilly/node_modules/unidragger/node_modules/unipointer
 @ ./~/draggabilly/~/unidragger/~/unipointer/unipointer.js 16:4-21:6

**Comment by desandro** [comment]
Sounds like a Webpack issue 883.

Install Draggabilly and [imports-loader](https://github.com/webpack/imports-loader) with npm.

``` bash
npm install draggabilly
npm install imports-loader
```

In your config file, `webpack.config.js`, use the imports loader to disable `define` and set `window` for `draggabilly` modules.

``` js
// npm <= v2
module.exports = {
  module: {
    loaders: [
      {
        test: /draggabilly/,
        loader: 'imports?define=>false&this=>window'
      }
    ]
  }
};
```

``` js
// npm >= v3
module.exports = {
  module: {
    loaders: [
      {
        test: /draggabilly|desandro|get\-size|classie|unidragger|unipointer|eventemitter/,
        loader: 'imports?define=>false&this=>window'
      }
    ]
  }
};
```

This hack is required because of an issue with how Webpack loads dependencies. **+1 webpack/webpack#883** to help get this issue addressed.

You can then require('draggabilly').

``` js
// main.js
var Draggabilly = require('draggabilly');

var draggie = new Draggabilly( '.item', {
  // options...
});
```

Run webpack.

``` bash
webpack main.js bundle.js
```

**Comment by geohuz** [comment]
Yeah! I just found the similar solution on the flicktiy site :-), thanks a lot!

**Comment by desandro** [comment]
With Draggabilly v2.1.0, I've resolved all the Webpack dependency issues. You can now `require('draggabilly')` with Webpack and not have to include any extra `webpack.config.js` code.

If you run into any other issues with Draggabilly and Webpack, please open a new issue.
