### ISSUE TITLE
how can i set a default position for an element?

### ISSUE THREAD

**Issue by emretekince** [desandro/draggabilly#112]
how can i set a default position for an element?

**Comment by desandro** [comment]
You can set `left` and `top` in CSS for the element. [See demo on CodePen](http://codepen.io/desandro/pen/c68ec2e6911ace863e34abeb3782daad/)

**Comment by emretekince** [comment]
when I set left and top, the position data of element starts from 0, 0..

Also I have another problem.
could you check this http://onungibiol.com/ ?
when I move the box which inside of the image frame, the box goes to top of the window. and I move again, it comes back to frame. it's strange..
