### ISSUE TITLE
dragEnd event  can`t get the pointer

### ISSUE THREAD

**Issue by Syses** [desandro/draggabilly#113]
![dragend_bug](https://cloud.githubusercontent.com/assets/7549358/12511023/168fc0ac-c149-11e5-9a92-fedcbf299aa8.png)

**Comment by Syses** [comment]
and  some other was  same to the dragEnd

**Comment by desandro** [comment]
Thanks for reporting this issue. On `dragEnd` on desktop, the `pointer` argument will be the `MouseEvent`.

> `pointer` - _Type_: `MouseEvent` or `Touch` - the event object that has `.pageX` and `.pageY`

From the look of your screenshots, that appears to be the case. Is there another bug? Can you put together a **reduced test case**? See [Contributing guidelines](https://github.com/desandro/draggabilly/blob/master/contributing.md#reduced-test-case-required)

**Comment by Syses** [comment]
![dragstart](https://cloud.githubusercontent.com/assets/7549358/12576715/a00e4d3a-c450-11e5-88e2-0a2a129fc8a9.png)

all event was the same result 
pointerDown
pointerMove
pointerUp
dragEnd
dragMove
dragStart
staticClick
