### ISSUE TITLE
can you support a option tansform

### ISSUE THREAD

**Issue by Syses** [desandro/draggabilly#114]
transform:true use css3 transform
transform:false don`t use css3 transform
if there are so many elements  in the draggabilly·s,  it will shake
i think  it  happen at the “proto.dragEnd” function 
![t](https://cloud.githubusercontent.com/assets/7549358/12614774/f9800772-c53c-11e5-8087-966b0980be17.png)

**Comment by desandro** [comment]
Thanks for your input. See #92 Closing here.

**Comment by Syses** [comment]
#92  [](https://github.com/desandro/draggabilly/issues/92)  is different  with this 
this issue means ,when i dragend the draggabilly`s element ,it will shake
