### ISSUE TITLE
Drag & throw physics

### ISSUE THREAD

**Issue by evolutionjay** [desandro/draggabilly#117]
can i throw it like this :
[http://greensock.com/throwpropsplugin](url)

**Comment by desandro** [comment]
Thank you for this feature request. **+1 this issue** if you'd like to see Draggabilly add throw physics

**Comment by bravokiloecho** [comment]
+1

**Comment by thomasdebruin** [comment]
+1

**Comment by desandro** [comment]
I have decided not to add this feature to Draggabilly. Thank you for your interest!
