### ISSUE TITLE
Change z-index when dragging

### ISSUE THREAD

**Issue by ASTN1** [desandro/draggabilly#119]
Hi,

I would like to set a CSS property (z-index: 9999) on each element that has been dragged.

I thought about using the dragEnd event, but 'pointer' isn't an object...
```
$draggable.on( 'dragEnd', function( event, pointer ) {
    pointer.css('z-index', '9999');
});
```

As far as I know there isn't a class for dragged elements...

Any idea?

**Comment by desandro** [comment]
Draggabilly adds `is-dragging` class. You can use CSS

``` css
.is-dragging {
  z-index: 2;
}
```

**Comment by ASTN1** [comment]
Thank you for your answer, but this class disappear as soon as you drop the div, isn't?

**Comment by desandro** [comment]
Try this code:

``` js
$draggable.on( 'dragEnd', function( event ) {
    $( event.currentTarget ).css({ zIndex: 9999 );
});
```
