### ISSUE TITLE
Click on div inside draggable div on Mobile Not Working

### ISSUE THREAD

**Issue by Coedcoe** [desandro/draggabilly#122]
I have a horizontal dragging menu that when on mobile, none of the links in the draggable div are clickable. I see there is a staticClick event but the documentation around how to use it is sparse. Is there no way to just say staticClick:true , and then static clicks work normally? My links all do different things and call different JS functions, so how can staticClick allow this?

**Comment by desandro** [comment]
I recommend you try the [back `handle` technique](http://codepen.io/desandro/pen/znAuH) so that inner elements are still interactable, but the element itself is still draggable.

**Comment by sandeep2021** [comment]
Hi ,
i have a problem which is similar to this in ios devices . i have a Bootstrap modal which is draggable but onclick events are not working for inside elements like close button . i have tried above " back handle technique ". but found no results can you help how can i allow onclick events inside draggable model?
