### ISSUE TITLE
changing the transform method to change the background-position-y only

### ISSUE THREAD

**Issue by sanjayaega** [desandro/draggabilly#124]
Hello, I am currently using your draggabilly for my code, and I have some custom modification on it. 
How if I want to change the `transform:translate3d()` into the`background-position-y:`?
I have tried but i still confuse on it. sorry I am newbie on javascript. Thanks for your reply :D

**Comment by desandro** [comment]
The element's style is set here:

https://github.com/desandro/draggabilly/blob/v2.1.0/draggabilly.js#L411-L419

You may want to try overwriting these methods.
