### ISSUE TITLE
Publish package to packagist and exclude dev files from release archives

### ISSUE THREAD

**Issue by mkungla** [desandro/draggabilly#126]
Since I am using mostly [packagist](https://packagist.org/) package manager with [Component Installer for Composer](https://github.com/RobLoach/component-installer) for front end stuff and found that you have packagist [account](https://packagist.org/users/desandro/) so it would be nice if this component would be available from packagist. 

Also when creating any of releases you could use .gitattributes to exclude `dev files` from release archives. Ones you have excluded in `bower ignore list`.

I have that all ready to go under [my fork](https://github.com/mkungla/draggabilly) so I can send you pull request related to this issue.

Just some toughts that in total this package could be submitted also under [`components/components`](https://github.com/components/components/issues).

**Comment by desandro** [comment]
Thanks for submitting this issue. I tried out Composer support about couple months ago. I can't say I'm happy with it. It's another package manager — one I don't quite understand that requires its own login, authentication, and maintenance. I'm not keen on adding Composer support to other libraries.

I'll keep the PR open for a bit to see if others are interested. Please See discussion in #127.
