### ISSUE TITLE
Draggabilly + packery and display attribute

### ISSUE THREAD

**Issue by mer23** [desandro/draggabilly#128]
I'm using packery and draggabilly to make a layout with draggable items. Sometimes I need to hide and show some of the items, the thing is, when items get shown after being hidden they act inconsistently (they bounce when dragged, the is-dragging state stays forever). Is there some way of achieving normal behavior of grid items after playing with their display attribute? Thanks.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).
