### ISSUE TITLE
emit dragStart when element starts moving, not on pointer down event

### ISSUE THREAD

**Issue by desandro** [desandro/draggabilly#13]
This is consistent with jQuery UI Draggable. It makes sense, as it prevents moving logic from being triggered when it doesn't have to.

I'm running into a problem on a Packery+draggable demo, trying use just pointer events. When item is 'clicked' (pointer doesn't move), I want to do different logic.

Eh, this may be problematic in the long run.

**Comment by netwire88** [comment]
Thanks, is this merged in v1.1.2 or should we take care of that in our own code?

**Comment by desandro** [comment]
This is likely to land in v1.2.0, which I am currently working on

**Comment by temuri416** [comment]
@desandro Is there an ETA on 1.2.0? Looking forward to it.

**Comment by rickhall** [comment]
+1

**Comment by desandro** [comment]
Draggabilly v1.2.0 has been released. Draggabilly now triggers [`dragStart`](http://draggabilly.desandro.com/#dragstart) when dragging first starts and [`pointerDown`](http://draggabilly.desandro.com/#pointerdown) on mousedown/touchstart/pointerdown. There's also a [`staticClick`](http://draggabilly.desandro.com/#staticclick) triggered to easily detect click/tap events. Give it a shot!

**Comment by temuri416** [comment]
Awesome, thanks a lot! Starting testing it :-)

**Comment by netwire88** [comment]
Thanks David. Can't wait to try it.
