### ISSUE TITLE
Drag outside overflow: auto div

### ISSUE THREAD

**Issue by Zeladgolan** [desandro/draggabilly#130]
Hi, 
I have a div with overflow hidden/auto, 
Whenever I'm trying to drag an element outside this div the element is hidden.
I've looked for many solutions (css, js) and didn't find anything.
Do you have one?
E

BTW 
adding position:absolute to the draggable element isn't a proper solution because it'll ruin the element position..

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Draggabilly. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/draggabilly/blob/master/contributing.md#reduced-test-case-required).

**Comment by Zeladgolan** [comment]
Hi, 
Thanks desandro.
Here's a test case, forked from demo:
http://codepen.io/thegenda/pen/oxQrpL

**Comment by desandro** [comment]
Thanks for that! You cannot drag the element outside its parent container because `overflow: hidden` prevents the draggable element from being displayed outside of the container. The only way to fix this is to either remove `overflow: hidden`, or have the draggable items HTML outside of the container.

**Comment by Zeladgolan** [comment]
Hi, 
Thanks for the answer. I know why it happens, I've looked for a workaround..
There's couple of workaround on different projects like draggable, and so..
Thanks anyway.

**Comment by Zeladgolan** [comment]
Checkout this workaround, 
I've update the codepen example.
All I did was to add this line to the dragStart function:
`instance.element.attributes[4].nodeValue = instance.element.attributes[4].nodeValue.replace("relative","absolute");`
It simply change the draggable element from relative to absolute.
Please tell me what you think :-).
May it worth adding this option to your project.
http://codepen.io/thegenda/pen/oxQrpL

**Comment by desandro** [comment]
Draggabilly will not work properly in this scenario. Sorry, there is no workaround that will be reliable.

**Comment by amitguptagwl** [comment]
I'm facing the same issue and found some [hack](https://codepen.io/osublake/pen/XJQKVX) for jQuery draggable . I hope something can be done for draggabilly as well?
