### ISSUE TITLE
jQuery-less dist files / .trigger check

### ISSUE THREAD

**Issue by silverwind** [desandro/draggabilly#133]
I'm using a custom build of jQuery that does not include `.trigger`,which results in an error when Draggabilly tries to call it. I've solved the issue now by loading Draggabilly before jQuery so I get the vanilla version of Draggabilly. As for a better solution, I'd suggest either:

1) Provide dist files for a pure vanilla version, with the jQuery parts removed. I'd love to see the optional dependency removed, which would reduce the size of this script significantly.

2) Add a check for `this.$element.trigger` on [this line](https://github.com/desandro/draggabilly/blob/ea0e4b420b8d04f13be90cbb205c913ed27f278c/draggabilly.js#L162).

**Comment by desandro** [comment]
Thanks for reporting this issue.

> I'm using a custom build of jQuery that does not include `.trigger`

This sounds like an edge case. If you're using jQuery, I expect `.trigger` to be there. Another solution is to fork Draggabilly and remove the jQuery parts. I'll leave that up to you. I appreciate your input here, but I feel this scenario is not significant enough to modify Draggabilly.

**Comment by silverwind** [comment]
> fork Draggabilly and remove the jQuery parts

That's just what I did. You should consider dropping support too 😉.
