### ISSUE TITLE
fixed and initial position.

### ISSUE THREAD

**Issue by guidoferreyra** [desandro/draggabilly#134]
Hi! 
I have elements with position: fixed and initial position of the elements setted with left and top. But when draggabilly is running it overrides the `position: fixed` style, adding `position: relative`, so my items are not in the initial position that I want.
Any idea how can I achieve this?

Thanks in advance!

**Comment by guidoferreyra** [comment]
I looked to the draggabilly.js and I've found that I can use `position: absolute` and this solves my issue, but when I start to drag, in the first mouse move the element is "teleported" a few pixels away the initial position and then it drags fine.

**Comment by desandro** [comment]
Thanks for reporting this issue. Draggabilly v2.1.1 has been released with a fix for this issue. Please upgrade and see how it works!

**Comment by guidoferreyra** [comment]
Thanks you!
