### ISSUE TITLE
How can a clone, copy or avatar be dragged instead of the original element?

### ISSUE THREAD

**Issue by ipavlic** [desandro/draggabilly#135]
I'd like to be able to "drag" a single element multiple times. So instead of dragging the element, I'd like to drag its copy, clone or avatar. How can I use draggabilly in that scenario? Can I fire some events on the clone that will initiate the drag once the original has been cloned into the DOM?

**Comment by desandro** [comment]
Hmm maybe. Draggabilly does not support cloning. Rather than trying to shoe-horn it in with Draggabilly, you may want to look at [jQuery UI Draggable](https://jqueryui.com/draggable/) or [Dragula](https://bevacqua.github.io/dragula/) which support cloning.
