### ISSUE TITLE
When disabled. preventDefault still runs on touch devices.

### ISSUE THREAD

**Issue by etoxin** [desandro/draggabilly#141]
I found that when you disabled `.disable();` Draggabilly you could not scroll on touch devices. I added this duck punch. Thought I'd open an issue before I started the PR.

    /**
     * Duck Punching Unidragger in Draggabilly.
     */
    Draggabilly.prototype._dragPointerDown = function( event, pointer ) {
      // track to see when dragging starts
      this.pointerDownPoint = window.Unipointer.getPointerPoint( pointer );

      var canPreventDefault = this.canPreventDefaultOnPointerDown( event, pointer );
      if ( canPreventDefault && this.isEnabled ) {
        event.preventDefault();
      }
    };

**Comment by desandro** [comment]
Good call! I've added a fix to check for `isEnabled` for preventDefault. This fix will be in the next release.

[If you like stickers](http://i.imgur.com/N5aLtsm.jpg), Email me yo@metafizzy.co so I can send some your way.

**Comment by etoxin** [comment]
Awesome.
