### ISSUE TITLE
Windows 10 touch support

### ISSUE THREAD

**Issue by gazzdingo** [desandro/draggabilly#143]
it works on edge with touch. but not on any other browser with touch any else has this problem

**Comment by desandro** [comment]
> not on any other browser with touch

Thanks for reporting this issue. What OS and what browsers?

**Comment by gazzdingo** [comment]
it was on Windows 10
i don't have the computer on me so i can't get the browser versions but i tested on chrome and firefox

I can update this once i get the laptop

**Comment by adam-lynch** [comment]
From what I can see:

- Doesn't nothing in Edge 38 on Windows 10.
- Works in Firefox 52 on Windows 10.
- Broken in Chrome 57 on Windows 10. The page is scrolled when you drag.
- Same^ in Opera 43 on Windows 10.
- Same^ in Chrome on my Nexus 5x, Android 7.1.2.
- Same^ in Safari on iPhone 6 Plus.
- Works fine in Chrome on an Acer tablet, Android 5.1.
- Works fine on iPad Mini (not sure which one), iOS 9.3.4.

:/

**Comment by desandro** [comment]
Please open a fresh issue if you run into trouble on Windows 10 with touch device.
