### ISSUE TITLE
Inline elements are invisible on moving

### ISSUE THREAD

**Issue by centurianii** [desandro/draggabilly#145]
Unless I change inline style adding rule: `display: inline-block;` elements remain invisible on moving.
But, as style is added by the code I have to make changes in the source code of the project(?).
Example: try to move `span`s in: `<ol><li><span>first</span></li><li><span>second</span></li></ol>`

What about drop events? How can we figure what elements live under the dropped element or when we have `dragenter`/`dragleave` events?

**Comment by desandro** [comment]
See https://github.com/desandro/draggabilly/issues/69#issuecomment-65297156
