### ISSUE TITLE
Add maintainers to the project.

### ISSUE THREAD

**Issue by aristidesfl** [desandro/draggabilly#149]
I see there are 10 open pull requests for a while now, so I assume @desandro has not had enough time to work on this lately. Is there someone who you think would be up to help maintaing this project?

**Comment by desandro** [comment]
Thank you for your interest in Draggabilly. For 2500+ GitHub stars, I'd say 15 open issues and 10 open PR's are pretty good. I'm a bit persnickity with how I deal with new features being added to libraries. Growing complexity makes my job as a maintainer harder.

If and when I'm ready to pass this project on to others I'll consider this request. Until then, I'm okay handling this repo.

**Comment by aristidesfl** [comment]
Please don't take this personally, it was not meant like that. More stars, means more people interested and more benefit from having the project well maintained. 
If pull requests remain open, and issues unanswered, it usually means that no one had time or interest to take care of them.
