### ISSUE TITLE
Lack of animation while dragging inline elements

### ISSUE THREAD

**Issue by aristidesfl** [desandro/draggabilly#152]
https://codepen.io/aristidesfl/pen/WpNEoX

**Comment by aristidesfl** [comment]
Looks like `transform` doesn't support inline elements. https://drafts.csswg.org/css-transforms-1/#transformable-element

Any ideas besides setting `display: inline-block`?

**Comment by aristidesfl** [comment]
Could we perhaps animate with `left/top` instead of `transform` when the element has `display:inline`?

**Comment by desandro** [comment]
Thanks for reporting this issue. Draggabilly does not support dragging inline elements. You'll have to use `inline-block` instead. See https://github.com/desandro/draggabilly/issues/69#issuecomment-65297156

**Comment by aristidesfl** [comment]
The issue is inline block doesn't doesn't replace inline in every situation, like for example with multiline text. In the scenario I'm using draggabilly for (chrome extension), converting elements to inline-block breaks the design.
