### ISSUE TITLE
Transformed (rotate or skew) items loose transformation during dragging

### ISSUE THREAD

**Issue by ldetomi** [desandro/draggabilly#156]
I use Draggabilly to drag&drop Flowchart items. No problems on _Process_ shape (a simple rectangle), but other shapes like _Decision_ (a "rhombus", so a rotated DIV) and _Input/Output_ (a "parallelogram", so a skewed DIV) loose recpectively `transform:rotate()` and `transform:skew()` during dragging, re-applying it after drop (eventual content of these elements with other tansformations applied is preserved). 

Please, can you solve it? I sincerely would avoid to replace transformations with img backgrounds to mimic shapes on regular rectangular div,

**Comment by desandro** [comment]
See #92 and #120. Closing here as a duplicate.
