### ISSUE TITLE
Please set the module can not stack up, how to deal with?

### ISSUE THREAD

**Issue by leefuwa** [desandro/draggabilly#159]
![1](https://cloud.githubusercontent.com/assets/15123526/26435051/145025b2-413f-11e7-8d4b-13e559e3a7d7.png)
The settings module cannot overlap

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Draggabilly. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/draggabilly/blob/master/contributing.md).

**Comment by leefuwa** [comment]
Set two DIV cannot overlap. Can this be configured?

**Comment by desandro** [comment]
Sorry, Draggabilly does not collision detection, outside of its `contain` feature.
