### ISSUE TITLE
Use Draggabilly with the Packery layout of Isotope

### ISSUE THREAD

**Issue by virgo79** [desandro/draggabilly#163]
Hi David,

is it possible to use draggabilly with Isotope implemented with the packery layout-mode?
Actually there is only the following link [https://packery.metafizzy.co/draggable.html](https://packery.metafizzy.co/draggable.html) that explains how to use draggabilly with Packery as stand alone.

Thanks in advance.

**Comment by desandro** [comment]
Hello! The Packery layout mode for Isotope does not support dragging. See https://github.com/metafizzy/packery/issues/46#issuecomment-18617291 for my reasoning
