### ISSUE TITLE
onClick event doesn't works on touch devices

### ISSUE THREAD

**Issue by robertsLando** [desandro/draggabilly#169]
I'm using Draggabilly on a Dashboard with widgets, widgets header has some controls, each control is bind to a click event (to resize edit etc.). Click works with Desktops but doesn't works on touch devices, it even doesn't work in Chrome Touch devices emulator.

**Comment by desandro** [comment]
Draggabilly has a [staticClick event](https://draggabilly.desandro.com/#staticclick) to help detect when click events occur without the pointer moving.
