### ISSUE TITLE
Draggabilly animation play multiple times

### ISSUE THREAD

**Issue by deybyd182** [desandro/draggabilly#170]
I'm having a problem with Draggabilly + Packery. When I create an exact copy of an item from #Packery_DIV_1 and append it to #Packery_DIV_2 the item at 'dragEnd' the animation is played twice (sometimes, multiple times).

Here is a gif of the problem
![problema](https://user-images.githubusercontent.com/31019120/30030842-9ded0a96-9154-11e7-98b1-e9ba6c5fc785.gif)

jQuery code

`
var copy = $(this).closest('.pnlCardReporte').clone();
 $('#Favoritos_TAB').find('.pnl_Reportes').append(copy[0]).packery('appended', copia[0]);
var draggie = new Draggabilly(copy[0]);
// bind Draggabilly events to Packery
$('#Favoritos_TAB').find('.pnl_Reportes').packery('bindDraggabillyEvents', draggie);
`

**Comment by desandro** [comment]
Looks like you may have a double transition bug. See related documentation for Isotope: https://isotope.metafizzy.co/faq.html#items-jump-after-transitioning-position

**Comment by deybyd182** [comment]
Thanks for your answer, but doesn't work... seems an Packery error 'cause is adding extra css properties...

I tried delete them, but Packery create them again at moving

![dfg](https://user-images.githubusercontent.com/31019120/30133115-3bb62130-9318-11e7-9ef4-a2efaf5b9738.png)

**Comment by desandro** [comment]
Given all the issues you are having with Packery and Draggabilly, I would consider trying another solution, like jQuery UI Sortable. Sorry, but I won't be able to provide a solution for this issue.
