### ISSUE TITLE
Getting the drag handle currently being used

### ISSUE THREAD

**Issue by nimgimmer** [desandro/draggabilly#171]
Hey I am having an issue with trying to get the current drag handle being used for the dragging. I see that each drag item can have multiple handles on it.

**Comment by desandro** [comment]
Thanks for opening this issue. Draggabilly doesn't provide an API for getting the specific handle. But you could do this using the [pointerDown event](https://draggabilly.desandro.com/#pointerDown). Try forking the CodePens so I can get a better idea of what you're trying to achieve.
