### ISSUE TITLE
Binding to Draggabilly events in Coffeescript

### ISSUE THREAD

**Issue by lorenzopt** [desandro/draggabilly#172]
I've trying to bind to the 'dragEnd' event in Coffeescript with packery, but the handler is not being called:

Here is my code:
` els = packery.getItemElements()

        for elem in els
          draggable = new Draggabilly( elem )
          packery.bindDraggabillyEvents( draggable )
          $(draggable).on 'dragEnd', (dragIns, event,) ->
            console.log event`

Where might I be going wrong? New to Coffeescript, by the way.

**Comment by desandro** [comment]
Sorry, I don't have experience with CoffeeScript. Try [forking this demo and getting your code to work](https://codepen.io/desandro/pen/yyRapr).
