### ISSUE TITLE
Interact with dropzones ?

### ISSUE THREAD

**Issue by kounelios13** [desandro/draggabilly#174]
Hello.I wan't to start using draggabilly.

I've been studying the API but I couldn't find anything about dropzones.

Does this library support dropzones?

Let's say I drag an image over a bin icon in my web page.When I drop the image in the bin icon I would like to notify the user(e.g. an `alert`).

Is that possible?

Thanks In Advance

**Comment by desandro** [comment]
> Does this library support dropzones?

Nope. Draggabilly does not have dropzones. But you could build on top of Draggabilly your own dropzones. That's what I did with [Packery](https://packery.metafizzy.co)

**Comment by q2apro** [comment]
Sorry to say, but not being able to determine the dropzone makes "draggabilly" pretty useless 😔
