### ISSUE TITLE
draggabilly and jqueryUI resizable  can't use cooperatively

### ISSUE THREAD

**Issue by yuncode** [desandro/draggabilly#175]
first  move parent Div ,
then resize child Div.  
finally child Div  display incorrectly

if remove the containment option   the case is ok.

demo [https://codepen.io/oceanstick/pen/Rjqxyj](https://codepen.io/oceanstick/pen/Rjqxyj)

**Comment by desandro** [comment]
If you're using jQuery UI resizable, then I recommend you use [jQuery UI Draggable](https://jqueryui.com/draggable/)

**Comment by yuncode** [comment]
@desandro i follow your recommendations. the jQuery UI Draggable is have the same incorrect effort.
so I think jqueryUI resizable  have bug.

**Comment by desandro** [comment]
In that case, than this isn't a bug with Draggabilly. Sorry, I won't be able to help here.
