### ISSUE TITLE
how can i use draggabilly in my vue project?

### ISSUE THREAD

**Issue by shouxianjun** [desandro/draggabilly#178]
i use npm install ,and when i use {var draggie = new Draggabilly()}, console.log is    { ReferenceError: Draggabilly is not defined" }

**Comment by desandro** [comment]
Sorry, I do not have any experience with Vue.

But you should be able to require Draggabilly

```
npm install draggabilly

``` js
var Draggabilly = require('draggabilly');
var draggie = new Draggabilly( element );
```

**Comment by cortesben** [comment]
@shouxianjun you need to `import * as Draggabilly from 'draggabilly/draggabilly';`

**Comment by Yusoo** [comment]
use directive
```
import Draggabilly from 'draggabilly'

export default {
  bind(el, binding) {
    new Draggabilly(el, binding.value)
  },
}
```
