### ISSUE TITLE
Getting the drop target element

### ISSUE THREAD

**Issue by joao-m-santos** [desandro/draggabilly#180]
Hello,

I'm having trouble finding a way to get the element where I dropped my draggable element. I can find the position but not the element that it was dropped into.

Is there a way in the plugin to get this or is this a feature that does not exist?

Thank you for your attention,
Best regards

**Comment by desandro** [comment]
Thanks for submitting this issue.

> Is there a way in the plugin to get this or is this a feature that does not exist?

Sorry, Draggabilly does not support drop targets. However, you can add a 👍 reaction to metafizzy/next-project#1 if you'd like to see a new library built for this purpose.
