### ISSUE TITLE
Draggabilly breaks clicks inside input element

### ISSUE THREAD

**Issue by cbou** [desandro/draggabilly#181]
If an input is inside a draggable element then a click on this input always puts the cursor at the end of the input.

https://codepen.io/anon/pen/qxKpdq

**Comment by desandro** [comment]
Thanks for reporting this issue! I'll have to take a look.

**Comment by desandro** [comment]
🎉 [Draggabilly v2.2.0](https://github.com/desandro/draggabilly/releases/tag/v2.2.0) has been released with a fix for this issue. 🎉

Please update! Closing this as resolved.

**Comment by cbou** [comment]
Great Thanks!
