### ISSUE TITLE
How to create range with two sliders?

### ISSUE THREAD

**Issue by shubich** [desandro/draggabilly#183]
I wanna create range slider like [this](https://plnkr.co/WL80md)
The most important feature is:
**Left slider shouldn't go beyond the right and vice versa**
![rangeslider](https://user-images.githubusercontent.com/29312810/36677886-63c673f6-1b20-11e8-8d2a-7fbaff0e27d5.png)

**Comment by desandro** [comment]
Yes, you can do this with Draggabilly. But, Draggabilly does not have any collision detection. So you'll have to build that yourself.
