### ISSUE TITLE
Site still says ONE and not ONCE

### ISSUE THREAD

**Issue by qm3ster** [desandro/draggabilly#184]
The README.md and typescript types have been updates, but the event binding method on the site is still ONE

**Comment by desandro** [comment]
jQuery uses `.one` method whereas vanilla JS uses `.once`. 

![screen shot 2018-03-02 at 11 42 18 am](https://user-images.githubusercontent.com/85566/36910472-d856a902-1e0e-11e8-9481-337d2ee9a716.png)

I'm having trouble finding the typo.

**Comment by qm3ster** [comment]
Maybe I was looking at different blocks on the site vs readme.
