### ISSUE TITLE
contain top-down, not bottom-up

### ISSUE THREAD

**Issue by zzzgit** [desandro/draggabilly#185]
https://codepen.io/zzzgit/pen/wyLjYN

when the content is heigher than the container, the title will be unreachable after a dragging action.
what i want is keeping the title alway in the container to make sure i can drag it anytime
could you tell me how to modify the source code?

**Comment by desandro** [comment]
Thanks for reporting this bug. I'll add a fix for this in the next release. Until then you can fix this by adding this code:

``` js
function applyGrid( value, grid, method ) {
  method = method || 'round';
  return grid ? Math[ method ]( value / grid ) * grid : value;
}

Draggabilly.prototype.containDrag = function( axis, drag, grid ) {
  if ( !this.options.containment ) {
    return drag;
  }
  var measure = axis == 'x' ? 'width' : 'height';

  var rel = this.relativeStartPosition[ axis ];
  var min = applyGrid( -rel, grid, 'ceil' );
  var max = this.containSize[ measure ];
  max = applyGrid( max, grid, 'floor' );
  return  Math.max( min, Math.min( max, drag ) );
};
```

See demo https://codepen.io/desandro/pen/vREyZZ

**Comment by zzzgit** [comment]
okay thanks
can you release a new npm package?

**Comment by desandro** [comment]
🎉 [Draggabilly v2.2.0](https://github.com/desandro/draggabilly/releases/tag/v2.2.0) has been released with a fix for this issue. 🎉

Please update! Closing this as resolved.
