### ISSUE TITLE
Overlapping items in Firefox (two column grid)

### ISSUE THREAD

**Issue by nldx** [desandro/draggabilly#186]
Draggabilly leads to overlapping items in the 2nd column of a two column grid in Firefox (current and recent previous releases), when items are moved in or into the second column (not occurring in all window widths, only in some, very strange issue):
https://codepen.io/robcs/pen/oqopyG

Please fix this soon

Best regards

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm already tracking this bug at metafizzy/packery#343
