### ISSUE TITLE
2.2.0 does not work on firefox 54

### ISSUE THREAD

**Issue by Yusoo** [desandro/draggabilly#187]
and also the website https://draggabilly.desandro.com does not work

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm on Firefox 60 and it's working fine. I'm not sure why its broken in Firefox 54.

[v2.2.0 did drop vendor prefixes](https://github.com/desandro/draggabilly/commit/8be460146f56ed2d657645f82b2f6bdf2e5c8cef), removing `mozRequestAnimationFrame`, but that would only affect Firefox <23.

**Add a 👍  reaction** to this issue if you ran into this issue. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
Can you confirm if this occurs on Windows or Mac?

**Comment by xcartmods** [comment]
So far, dragging not working in FF 52 and 56 (64-bit) on Windows 7.
Chrome 65 is all good.

**Comment by Yusoo** [comment]
windows 10
