### ISSUE TITLE
Distinguish on click event whether element was dragged or not

### ISSUE THREAD

**Issue by gobengo** [desandro/draggabilly#19]
Food for thought. Let's say I have an element. A user may drag it about and drop somewhere else. They may also just quickly click on like they would a link. This element is being managed by Packery.

The question is, what's the best way to do different things for these behaviors? By default, the click handler will be fired whenever the element is dragged. But in the click handler you have no way to tell if the element was actually moved, or whether it was a quick-click.

A solution for this is to add a class to the element on 'dragMove', and remove that class only once you've done something after 'dragEnd'. Like packery's 'dragItemPositioned' event. The click handler fires between these two moments, so your click handler can check for that class and return early if it was recently dragged, so as not to fire 'quick click' behavior after a drag.

*Is this the best way to accomplish this?*

Example.

Add a 'was-dragged' class between dragEnd and dragItemPositioned:
https://github.com/gobengo/streamhub-packery/blob/master/src/main.js#L46

Return early in click handler if it was recently dragged:
https://github.com/gobengo/streamhub-packery/blob/master/examples/mediawall/index.html#L77

**Comment by desandro** [comment]
Draggabilly v1.2.0 has been released. It now triggers [`staticClick`](http://draggabilly.desandro.com/#staticclick) so you can detect when a click has occurred, rather than a drag. Give it a shot!

drag-start branch has been removed.

**Comment by temuri416** [comment]
Fantastic job, everything is working as expected! Thank you so much.
