### ISSUE TITLE
Do not allow blank space in grid / switch element places ?

### ISSUE THREAD

**Issue by pixedd** [desandro/draggabilly#194]
Hello !

I've got a grid (with packery) and i'm using Draggability with it, I would like to prevent "spaces" in my grid when dragging or creating a new row when dragging.

Is there a way to only switch places between elements without creating any empty block in my grid ?

**Comment by desandro** [comment]
This is a Packery issue. You may be interested adding back Packery v1's drag layout behavior. See  metafizzy/packery#353
