### ISSUE TITLE
cannot drag vertically when container's height get very large

### ISSUE THREAD

**Issue by adajoy** [desandro/draggabilly#205]
environment: IE11 WIN10 1903

this issue only happen with IE
this maybe a problem with getComputedStyle() will return negative value in IE when value get large, like 300000px.

**Test case:** https://codepen.io/adajoy/pen/eYOBwYy

codepen doesn't support ie, you can open the pen with other browsers, copy the code and run it locally to reproduce it

**Comment by andrew2558** [comment]
My page reads as follows.

The problem is that when I use draggabilly to drag the move-line, dragging to the left is fine, but when I drag it to the right, it doesn't work in the area where the tinymce compiler is located. How do I fix this problem?

enter image description here
![wo7Y8](https://user-images.githubusercontent.com/25080605/89745628-cc69ae80-dae7-11ea-9bea-8be4d1866c0f.gif)

```html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>TinyMCE Drag</title>
 <script src="../lib/jquery3.5.1/jquery-3.5.1.js"></script>
 <script src="../lib/tinymce_5.4.0/js/tinymce.min.js"></script>
 <script src="../lib/draggabilly/draggabilly.pkgd.min.js"></script>

 <style>
 html,
 body {
 margin: 0;
 padding: 0;
 height: 100%;
 width: 100%;
 }
 .all-warp {
 display: flex;
 flex-direction: row;
 width: 100%;
 height: 100%;
 }
 .left {
 width: 200px;
 background-color: burlywood;
 }
 .move-line {
 width: 4px;
 background-color: crimson;
 cursor:e-resize;
 }
 .editor-warp {
 flex-grow: 2;
 }
 </style>
</head>
<body>
 <div class="all-warp">
 <div class="left"></div>
 <div class="move-line"></div>
 <div class="editor-warp">
 <textarea id="editor"></textarea>
 </div>
 </div>

 <script>
 $(document).ready(function () {
 var $draggable = $('.move-line').draggabilly({
 axis: 'x',
 containment: '.all-warp'
 })
 });
 tinymce.init({
 selector: '#editor',
 menubar: false,
 statusbar: false,
 language: 'zh_CN',
 resize: false,
 height:500,
 });
 </script>
</body>
</html>
```
