### ISSUE TITLE
click inside draggable container doesn't work on mobile devices

### ISSUE THREAD

**Issue by williharder** [desandro/draggabilly#208]
I hate to open a new issue, that was already talked about in most aspects, but I spent almost the entire day to debug the code or try to get my head around the fact, that on mobile (iPad/Tablet) all the links, buttons inside the `draggable` containers are not working. Weirdly enough it recognizes mouseover interactions. This is only visible on a native environment. Inside the devtools, when using the mobile agent it works. 

Unfortunately the suggested solution with using a handle that is behind all the interactive elements doesn't cut it for me, since the interactive content in my container are taking up all the space. 
And the idea to use the `staticClick` doesn't seem to work neither, since I need to be able to listen for the click on the button or links. I would be so immensely thankful and happy, if you could maybe give some pointers on how I could achieve what I want with `staticClick` or provide some answers, why it's not working anyway. 

Thank you! 

**Test case:** http://dragging.willi-harder.de/

**Comment by owen-m1** [comment]
what is the solution? @desandro
