### ISSUE TITLE
pass handle as element???...

### ISSUE THREAD

**Issue by mikila85** [desandro/draggabilly#209]
why not allow to pass handle as element???

**Comment by desandro** [comment]
Thanks for this feature request. **Add a 👍  reaction** to this issue if you would like to see `handle` be set with an Element. added. Do not add +1 comments — [They will be deleted](https://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
Draggabilly v3 has been released, now with updated `handle` behavior. You can set it to a single element or a Array or NodeList of elements

``` js
// select all .handle children with selector string
handle: '.handle'

// set as element
handle: element.querySelector('.handle')

// set as array or NodeList
handle: [ element.querySelector('.handle1'), element.querySelector('.handle2') ]
```

Please try it out and report back with any issues!
