### ISSUE TITLE
Demonstrate best way for non-draggable stuff

### ISSUE THREAD

**Issue by desandro** [desandro/draggabilly#30]
Like if you have a draggable element and you don't want other stuff to be draggable.

**Comment by joeclayallday** [comment]
I used the :not() selector: and it worked for me.

$grid.find('.drag-item:not(#dont-drag-item)').each( function( i, gridItem ) {
     var draggie = new Draggabilly( gridItem );
     $grid.packery( 'bindDraggabillyEvents', draggie );
   });
