### ISSUE TITLE
1.0.7 does not work with touch on Surface 2 IE11/Chrome and Lumina Windows Phone 8 IE10

### ISSUE THREAD

**Issue by cgerikh** [desandro/draggabilly#41]
I did some testing on these devices and:

On Surface 2 Pro running IE11
- works with the stylus as intended
- does not work with touch. It starts dragging and then a split second later stops.
- If it's bound to packery, the item begins to dragg and then snaps back in to place a second later as it if loses focus of touch.

On Surface 2 Pro running Chrome
- works with stylus as intended
- items just bound to draggabilly work with touch
- items bound to packery and bound to draggabilly break/lose touch 50% of the time and then packery just breaks down (items randomly jump within the grid here & there)

On Lumina WP8 using IE11
- same effect as touch on Surface 2 if you're using your finger/touch/no stylus.

Kind of a PAI and we can thank MS for all their pointer changes, but just an FYI. David if you need help testing and you don't have these devices, I can help :)

Chris

**Comment by desandro** [comment]
MS pointer events were added in v1.1.0. Closing as fixed.
