### ISSUE TITLE
how to drag item larger than its container but still be 'contained'

### ISSUE THREAD

**Issue by alycda** [desandro/draggabilly#46]
Thank you for this plugin, I would like the containment option to also work if the element being dragged is larger than its container. Once you get to the edge of the dragged element, you should not be able to drag further away from the edge (thus cropping the inner element OR showing too much space/padding by dragging it away from the edge). Do you think something like this is possible? It's for a responsive site I'm working on, so the values need to be recalculated on window resize (but the draggable container stays the same width).

**Comment by danhumaan** [comment]
I know this is quite an old request, but I wondered if this is something that's been addressed or worked into the library? This is precisely something I need to implement.

**Comment by desandro** [comment]
Sorry, Draggabilly does not support this feature. After 2 years of following this issue, it looks like it hasn't gained enough public interest. Closing for now :strawberry:
