### ISSUE TITLE
Multiple drag in iPad;

### ISSUE THREAD

**Issue by sajus** [desandro/draggabilly#48]
In tablet devices we can selected multiple drag elements with our fingers, and we can drag all of them together. Can we have any flag to force just one drag at a time. Since we have 'is-dragging' we can check if there exist any element which is currently dragging.

**Comment by desandro** [comment]
You can do this with `disable` and `enable` methods. Here's how to do it with jQuery. See demo http://codepen.io/desandro/pen/MYPoPG?editors=001

``` js
var $draggies = $('.draggie').draggabilly();

// disable non-dragging draggies
$draggies.on( 'dragStart', function() {
  $draggies.each( function( i, draggieElem ) {
    var draggie = $(draggieElem).data('draggabilly');
    if ( !draggie.isDragging ) {
      draggie.disable();
    }
  });
});

$draggies.on( 'dragEnd', function() {
  $draggies.draggabilly('enable');
});
```


Or vanilla JS: http://codepen.io/desandro/pen/yyxPdQ
