### ISSUE TITLE
Constrain X & Y movement with SHIFT key

### ISSUE THREAD

**Issue by temuri416** [desandro/draggabilly#53]
Would it be possible to add a feature that would force movement of dragged objects only along X or Y axis when SHIFT key is held.

Thanks!

**Comment by temuri416** [comment]
@desandro Any hope that http://codepen.io/desandro/pen/ogvVLw would make it to 1.2.1?

Cheers!

**Comment by desandro** [comment]
If this issue gets enough **+1**, I'll consider it.  When [I tweeted it](https://twitter.com/desandro/status/532152315453898752), it got a fair amount of engagement, so there definitely is a fair amount of interest.

**Comment by desandro** [comment]
Looks like no one else has +1'ed, so I'm going to close this feature request. Thanks again for bring up this issue!
