### ISSUE TITLE
Does not work well with SVG

### ISSUE THREAD

**Issue by tjosseau** [desandro/draggabilly#59]
Hi there ! I just found an issue with Internet Explorer (tested with 11), errors occure while dragging SVG elements.

Here is a test : http://jsfiddle.net/Totjoss/MJJH8/

**Comment by desandro** [comment]
Thanks for reporting this issue. I haven't completely tested Draggabilly with SVG, so I'm surprised if it works at all. From what I can guess, it should work on `<svg>` elements, but not inside SVG nodes.

**Comment by desandro** [comment]
Closing this issue as others have not chimed in reporting the problem. Please speak up if you run into troubles with Draggabilly and SVG.
