### ISSUE TITLE
Applies Position relative on init if the element is fixed positioned

### ISSUE THREAD

**Issue by ahmed1490** [desandro/draggabilly#60]
In `_create` we have..

```
  // set relative positioning
  var style = getStyle( this.element );
  if ( style.position !== 'relative' && style.position !== 'absolute' ) {
    this.element.style.position = 'relative';
  }
```

**Comment by tiagomsmagalhaes** [comment]
Hi...

It was really weird to find this as a solution for draggabilly, when in the website this option is absent. It makes me think that there are another options for draggabilly...

**Comment by suhaotian** [comment]
what abput fixed position style?

**Comment by z1haze** [comment]
@desandro the link you shared for this was related to masonry.. when i tried the same option with draggabilly, nothing happened

**Comment by desandro** [comment]
This issue was fixed in v2.1.1. See #134

**Comment by z1haze** [comment]
I appreciate that but I have already read that ticket and this is not my case. My elements are not position fixed, they are already styled with position absolute. In fact my temporary solution was just to !important the absolute position in my CSS to override the relative that is applied from the plugin. I checked I am using the exact version claiming to have fixed this, and even looked at the source where it hard coded position relative. Please take another look and tell me what actually needs to be done to fix this.

**Comment by z1haze** [comment]
please see this, by default if the element is styled with position absolute it forces them to be relative. why is this?

```js
proto.option = function( opts ) {
  extend( this.options, opts );
};

// css position values that don't need to be set
var positionValues = {
  relative: true,
  absolute: true,
  fixed: true
};

proto._create = function() {

  // properties
  this.position = {};
  this._getPosition();

  this.startPoint = { x: 0, y: 0 };
  this.dragPoint = { x: 0, y: 0 };

  this.startPosition = extend( {}, this.position );

  // set relative positioning
  var style = getComputedStyle( this.element );
  if ( !positionValues[ style.position ] ) {
    this.element.style.position = 'relative';
  }

  this.enable();
  this.setHandles();

};
```

**Comment by desandro** [comment]
I'm not able to reproduce that bug. See demo https://codepen.io/desandro/pen/ac004626de5f69410b880d4bd215e2f8/

**Comment by z1haze** [comment]
Yea, i can't seem to cause it now either - I must have had an issue somewhere.
