### ISSUE TITLE
Options Grid snap on dragEnd

### ISSUE THREAD

**Issue by A-Monkey** [desandro/draggabilly#65]
Hi man,

Is it possible to add/set the "grid" option on "dragEnd", so the object
is free to move outside of the "grid", and when you release it on "dragEnd"
it adapts and snaps into place (grid).

If you have a solution without digging around in core files or 
maybe motivation to add a new option for this it would be seriously super duper amazing mega
awesome...

Best regards /
Monk

```
dragger = new Draggabilly(elem, {
       containment: true,
       grid: [ 0 , 0 ]
});

dragger.on('dragStart', function () {
       dragger.options.grid = [0, 0];
});

dragger.on('dragEnd', function () {
       dragger.options.grid = [100, 100];
});
```

**Comment by desandro** [comment]
I've updated the code so it's not munging with `prototype.dragEnd`. This code works with both Draggabilly v1.1.x and v1.2.x. http://codepen.io/desandro/pen/gbYELj

``` js
var draggie = new Draggabilly('.draggie');
var grid = [ 40, 40 ];

draggie.on( 'dragEnd', function() {
  draggie.position.x = applyGrid( draggie.position.x, grid[0] );
  draggie.position.y = applyGrid( draggie.position.y, grid[1] );
  draggie.setLeftTop();
});
```

or with jQuery

``` js
var $draggable = $('.draggie').draggabilly();
var draggie = $draggable.data('draggabilly');
var grid = [ 40, 40 ];

$draggable.on( 'dragEnd', function() {
  draggie.position.x = applyGrid( draggie.position.x, grid[0] );
  draggie.position.y = applyGrid( draggie.position.y, grid[1] );
  draggie.setLeftTop();
});
```
```

**Comment by A-Monkey** [comment]
Aaahh cool man, looks great, thanks a lot !!
