### ISSUE TITLE
Browser & device support

### ISSUE THREAD

**Issue by desandro** [desandro/draggabilly#7]
I'm limited to testing with what I've got lying around. I would very much appreciate if you can test out http://draggabilly.desandro.com/ and report back. That'd be delightful.

Unless noted with a :broken_heart:, Draggabilly works on the following devices and browsers. See #8 for broken devices and browsers.
- [x] Google Chrome, Firefox, Safari on OSX
- [x] IE8, 9
- [x] IE10
- [x] [Android 2.2](https://twitter.com/GarciaWebDev/status/313749660206522370)
- [x] Android 2.3 [HTC Desire](https://twitter.com/miss_jwo/status/315019996877176833)
- [x] Android 4.1: [Chrome on Android 4.1.1 ](https://twitter.com/kleinmatic/status/314936200630779904), [Galaxy Note II](https://twitter.com/bakytn/status/314941040782090240)
- [x] Android 4.2: [Galaxy Nexus Android 4.2.2 - Chrome 25](https://twitter.com/joshwins/status/314936436384210944), [Samsung Galaxy S2, chrome browser](https://twitter.com/HeyDanReeves/status/314938611688681472), [android 4.2.1 in Native, Chrome, & Firefox](https://twitter.com/getsetbro/status/314940261623009280)
- [x] iOS 5 (iPhone 4), iPad 2
- [x] Opera Mobile Emulator
- [x] :broken_heart: Opera Beta on Android
- [x] Microsoft Surface
- [ ] Any Android tablet
- [x] Kindle Fire ([1st gen](https://twitter.com/chris_frees/status/314936750638239745))
- [x] :broken_heart: Microsoft Windows Phone [Window Phone 7](https://twitter.com/amarchadgar/status/314977927508946944)
- [ ] Google Chromebook Pixel (which has support for both touch and mouse events)
- [x] [Wii U](https://twitter.com/jmk1ng/status/314955959971766272)
- [x] :broken_heart: [Nokia Lumia 920](https://twitter.com/kevmcdonk/status/315001692351496192)
- [x] BlackBerry 10 browser

... and lots more. Feel free to chime if you have tested it in something else.

**Comment by mebibou** [comment]
Works on Nexus 7 with Android 4.4.2 in a WebView and on Chrome
Works on Microsoft Surface Pro 2 (IE 11)

**Comment by sahanbsb** [comment]
On IE 10 (10.0.9200.17457), when the draggable element is clicked for the second time, IE window loses focus and send back of other opened windows. But IE is still active on the task bar. When the IE window is pull to front, the draggable element is following the mouse pointer even without dragging.

**Comment by desandro** [comment]
Closing this issue as it's old old old by now. If you run into specific device/browser issue, please open a new issue.

Thanks for the contributions! 🐳
