### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by chiplay** [desandro/draggabilly#72]
Hey @desandro - first off, thanks for the great library!

Is there any memory concern from creating a new Draggabilly?  I didn't see any type of 'destroy' method to unwind event handlers / delete `el` references - have you run into issues with this in single page apps where draggable el's are created and removed from the dom repeatedly?

**Comment by kurttheviking** [comment]
hello all, it looks like the npm version is still 1.1.1 (I noticed this detached node issue today) -- is it possible to get an updated version on npm? much appreciated!

**Comment by desandro** [comment]
Ah, good catch :baseball:. [Published v1.1.2 to npm](https://www.npmjs.com/package/draggabilly)

**Comment by kurttheviking** [comment]
:+1:
