### ISSUE TITLE
Problem with % and position absolute in Safari

### ISSUE THREAD

**Issue by botelho** [desandro/draggabilly#75]
When using percentages for positioning an absolute element the top and left do not get calculated correctly in Safari (tested with Safari 6.2.2 on OS X 10.8.5). The top and left applied seems to be the percentage value in pixels.
Here's an example: http://jsfiddle.net/rp7z8zwz/

**Comment by botelho** [comment]
Seems to be related to this: https://bugs.webkit.org/show_bug.cgi?id=29084

**Comment by desandro** [comment]
Thanks for reporting this. See related #15

**Comment by desandro** [comment]
Closing as a duplicate.
