### ISSUE TITLE
.destroy() error: is not a function

### ISSUE THREAD

**Issue by di5abled** [desandro/draggabilly#76]
when I want to desroy my draggabilly instance the following error is thrown: 

```
Uncaught TypeError: undefined is not a function
```

I installed it via Bower *v1.1.1* and the only aditionall script I'm using on this side is jQuery *v1.11.2*

**Comment by desandro** [comment]
Sorry to hear you're running into trouble here. If you have a test case, that'd help figure out what's going on. I wasn't able to reproduce the error with this test case: http://codepen.io/desandro/pen/Wbdygm

Can you confirm you are using `draggabilly.pkgd.js` and no `draggabilly.js` ?

**Comment by di5abled** [comment]
Version `v1.1.2` which you are using fixed the problem, but this version isn't available via bower yet? 

Another Question, what is the best way to let your script recalculate all values eg. when the container changed in size?

**Comment by desandro** [comment]
Whoops! Tag `v1.1.2` pushed. It should be available via Bower now.

> what is the best way to let your script recalculate all values eg. when the container changed in size?

Unfortunately, there is no good way to do this now. This a duplicate request of #34. Follow that issue for updates.

**Comment by di5abled** [comment]
great! thank you a lot, I will follow the issue and close this for now!
