### ISSUE TITLE
Listening to the other drag events

### ISSUE THREAD

**Issue by markusdrake** [desandro/draggabilly#77]
I can't seem to listen to the other half of the events when using draggabilly. Am I correct in the assumption that dragging (with this script) won't trigger `dragenter`, `dragleave`, or `drop` events in the DOM? 

I was hoping to use this as an alternative to jQuery UI and having to deal with touch events. But if I can't listen to the events it's no use to me and I'll have to pick out pieces of UI. 

I did try droppabilly, seems to only work on one element. I'm not sure that dragleave worked at all, but I was able to trigger enter and drop. I have multiple elements on the screen that can accept a drop. 

Thanks for any direction or help you can give me,

**Comment by desandro** [comment]
Hi, thanks for taking a shot with Draggabilly. Draggabilly does not use HTML5 drag and drop API.

Draggabilly does emit events that you listen to: http://draggabilly.desandro.com/#events
