### ISSUE TITLE
Support Zoomed window

### ISSUE THREAD

**Issue by mebibou** [desandro/draggabilly#80]
When using on a zoomed window, position of the dragged element does not take the zoom into account, therefore it doesn't follow the pointer.

Demo : http://codepen.io/anon/pen/dPwBBa

**Comment by desandro** [comment]
Thanks for reporting this issue. [`zoom` is a non-standard feature](https://css-tricks.com/almanac/properties/z/zoom/). I'm closing this as `wontfix`.
