### ISSUE TITLE
Support 'transform: scale()' on body

### ISSUE THREAD

**Issue by mebibou** [desandro/draggabilly#81]
When using css `transform: scale()` on the body, position of the dragged element does not take the scale into account, therefore it doesn't follow the pointer.

Demo : http://codepen.io/mebibou/pen/yyZRXG

**Comment by desandro** [comment]
jQuery UI Draggable doesn't support this either. See http://codepen.io/desandro/pen/RNveEL This is a specialized edge case. If a transform or zoom is being applied, I'll leave it to the developer to resolve this. This is outside Draggabilly's scope.
