### ISSUE TITLE
Getting left position while dragging

### ISSUE THREAD

**Issue by babysteps** [desandro/draggabilly#88]
I am using draggabilly with the following settings:

{ axis: 'x', containment: [containerElement], grid:[10,0] }

to allow dragging left and right within the container on a 10px grid increment.  During the 'dragMove' event I would like to get the current 'left' position of the drag element (position from the left of the container).  Is this possible?  The pointer object returns where the pointer is, but I want to know where the draggable element is.  I have seen in the inspector that it is using transform: translate3d() to reposition the element, but have not had any luck in getting that value during the 'dragMove' event.

Thanks in advance for your help.  This is a great plugin!

**Comment by desandro** [comment]
See [CodePen - Draggabilly - dragMove with jQuery](http://codepen.io/desandro/pen/gbBwQe). Use `draggie.position`

**Comment by babysteps** [comment]
Thank you so much!  It works perfectly.

**Comment by z1haze** [comment]
how about without jquery?
