### ISSUE TITLE
Scrolling through a list of draggable elements

### ISSUE THREAD

**Issue by lopeax** [desandro/draggabilly#94]
Making a 'snappie' style version of draggable here: http://codepen.io/zephyr/pen/oXpOdW

Running into a couple of bugs however.

1) On mobile devices, even though the drag is constrained to the x axis, it is tough to get vertical scroll to work for it (even though the snap works perfectly, except it seems to be a bit jagged on mobile, though that may just be my amazon fire phone). I can't think of a way to make it detect if it is scrolling or not (vertically only). tl;dr scroll in vertical, drag in horizontal.

2) On desktop versions, if the mouse escapes the screen while the element is being dragged, the user needs to click back into the window to stop it from dragging. This also occurs if the user drags outside of the mobile screen, and then needs to drag again to fire the dragEnd event (might be just on amazon fire phone)

Great library though!

**Comment by desandro** [comment]
1. Draggabilly  does not account for vertical mobile scrolling — like [Flickity](http://flickity.metafizzy.co/) does. If you have a page full of draggable elements, it will be tough to scroll.
2. This occurs because of the CodePen is in an `iframe`. Try the [debug version](http://s.codepen.io/zephyr/debug/oXpOdW?)

**Comment by lopeax** [comment]
Ah ok then, thanks for the help!

**Comment by kabalage** [comment]
I have a similar problem to 1). For me a good solution would be to provide an option to only activate dragging after long press. If you don't have the time to implement this feature, I would try. Please let me know.

**Comment by lopeax** [comment]
Having tried Flickity, it fits perfectly for what I wanted to do (thanks desandro, ended up buying a licence as well), have you checked that out?

**Comment by kabalage** [comment]
I'd like to implement drag&drop between multiple scrollable containers. Unfortunately Flickity does not help here. :confused:

**Comment by horasikus** [comment]
any news on this? 
codepen links are broken

kabalage, did you achieve to only activate dragging after long press? do you have an example?
i have a page full of draggable elements and new Draggabilly(...) kills the vertical scroll on mobile devices, even with the draggie element .disable()
thanks desandro for your libraries.
