### ISSUE TITLE
The window will switch when the first click in IE8

### ISSUE THREAD

**Issue by NexusLee** [desandro/draggabilly#96]
Is that a bug?

**Comment by desandro** [comment]
Thanks for reporting this issue. This is most likely a proper bug. I'm going to be dropping support for IE8 at the end of 2015, so I might leave this issue unresolved.

**Comment by desandro** [comment]
Draggabilly v2 has been released and IE8 support is now officially dropped. Sorry, I will not be able to fix this this one.
